# Generated by Django 4.2 on 2025-01-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="airplan",
            old_name="seats",
            new_name="seats_in_row",
        ),
    ]
