# Generated by Django 4.2.9 on 2025-01-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_rename_seats_airplan_seats_in_row"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="crew",
            field=models.ManyToManyField(to="airport.crew"),
        ),
    ]
