# Generated by Django 4.2.9 on 2025-01-06 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0004_flight_crew"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Airplan",
            new_name="Airplane",
        ),
        migrations.RenameModel(
            old_name="AirplanType",
            new_name="AirplaneType",
        ),
        migrations.RenameField(
            model_name="airplane",
            old_name="airplan_type",
            new_name="airplane_type",
        ),
        migrations.RenameField(
            model_name="flight",
            old_name="airplan",
            new_name="airplane",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taken_tickets",
                to="airport.flight",
            ),
        ),
    ]
