# Generated by Django 4.2.9 on 2025-01-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0005_rename_airplan_airplane_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="route_description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
